services:
  - name: google
    url: https://www.googlers.com
    method: GET
    type: http
    body: ""
    interval: 5s
    headers:
      - name: "Content-Type"
        value: "application/json"
    response:
      status: 200
      body: ""
    alerts:
      - name: devops
        type: email
        to: ""
        failure: 3
        success: 3
        send-on-resolve: true
      - name: manager
        type: slack
        to: ""
        failure: 3
        success: 3
        send-on-resolve: true
  - name: facebook
    url: https://www.facebook.com
    method: GET
    type: http
    body: ""
    interval: 5s
    headers:
      - name: "Content-Type"
        value: "application/json"
    response:
      status: 200
      body: ""
    alerts:
      - name: devops
        type: email
        to: ""
        failure: 3
        success: 3
        send-on-resolve: true
      - name: manager
        type: slack
        to: ""
        failure: 3
        success: 3
        send-on-resolve: true
